name:  primeira pipeline
on:
  push:
    branches: "main"
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Meu Primeiro Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira ação"
        run: echo "Hello World !!!"
      - name: "Minha segunda ação"
        run: |
          echo "Criando do priemiro worlflow"
          echo "Parabéns !!!"
      - name: "Script Python"
        run: |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Install NodaJS environment"
    runs-on: ubuntu-latest
    needs: "primeiro-job"
    steps:
      - name: "Verificar NodeJS version"
        run: node --version
      - name: "nodeJS definition version"
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'
      - name: "Update NodeJS version"
        run: node --version
